### ISSUE TITLE
Supply additional unit tests

### ISSUE THREAD

**Issue by joergbrech** [hbrs-cse/Modellbildung-und-Simulation#104]
Currently, some exercises provide unit tests, so that the students can check their work. We should think how we can gently introduce students to the concepts and when and where we should use them without causing confusion.

One idea would be to add an introductory exercise to unit tests: Write a simple function with simple unit test

_Edit (Philipp)_: From #17 : "Die Verkehrssimulationsaufgabe bietet sich an für unit tests. Die müssten noch implementiert werden, siehe #16 "

**Comment by PhiSpel** [comment]
I don't think we need too many unit tests - though they would still be nice to have!
@Florian314 did you have the impression during #469 that students would still need more unit tests?

**Comment by Florian314** [comment]
I think that it would only be a nice-to-have. I think there are currently enough unit tests for the students that want to use them and the students who don't want to use them don't have to.
