### ISSUE TITLE
Contributing / How to set up software (Windows)

### ISSUE THREAD

**Issue by rstrickstrock** [hbrs-cse/Modellbildung-und-Simulation#252]
The contributing section starts with git and anaconda commands. Before that the softwares needs to be installed.

Add a guide how to set up the system to be able to contribute (Windows/Linux?/Mac?).

- required accounts (and access)
- software(s)
- installation and environmental set up

- [ ] naming for branches: [issue-ID]-[initials]/[name_of_branch]

**Comment by PhiSpel** [comment]
In case you worked on Linux, I can share my experience using Windows (setting up WSL, Ubuntu, CPU Virtualization, etc.)

**Comment by joergbrech** [comment]
WSL is not needed, just convenient. Everything we do should be platfform-independent

**Comment by rstrickstrock** [comment]
I recently set up an environment on Windows:
- Anaconda App to launch Jupyter-Notebooks
- Github Desktop to pull the project, manage branches etc.

the workflow is to pull the current status, edit it locally via Anaconda/Jupyter-Notebook and push the changes afterwards. It's pretty convenient and straight forward, if everything is set up.

Lily switched notebooks so I had to reinstall everything and was wondering what is needed and what to install. So I want to create a quick guide, probably with images, showing what to get where and how the workflow works.

Afterwards I might do the same for Linux.

**Comment by PhiSpel** [comment]
Did you also manage to install the octave kernel in Jupyter? `sudo apt-get` did not work for me and the `octave` package is only available for Linux, for windows only `octave_kernel` is available and does not load into jupyter (maybe this is a reference in `requirements.txt`?). Did this work better for you?

A standard workflow would surely be very nice :)

**Comment by PhiSpel** [comment]
@rstrickstrock do you have new insights which we can discuss tomorrow?

**Comment by PhiSpel** [comment]
Make two versions for first-setup: (1) Linux subsystem on Windows and (2) Linux

**Comment by PhiSpel** [comment]
Hey @Florian314 I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/modellbildung-und-simulation-612fbfd8668c0f0010bd08aa/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account.
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by Florian314** [comment]
Thats a no from me. Until now i didn't realy use git and anaconda commands, so i don't have the know-how to do this task
