### ISSUE TITLE
Live code functionality puts "copy to clipboard" in code boxes

### ISSUE THREAD

**Issue by m-r-schenk** [hbrs-cse/Modellbildung-und-Simulation#256]
When Thebe is launched to start live coding, the "Copy to clipboard" button turns into text, making the code unable to run.

This happens only on the website. Doing this on a local build does not cause this error.

![image](https://user-images.githubusercontent.com/57954821/154275511-aa1ba0d5-ccd9-4ecb-a3f5-e81e959b272d.png)

**Comment by joergbrech** [comment]
https://github.com/executablebooks/thebe/issues/537

**Comment by joergbrech** [comment]
Should be fixes in latent jupyter book version

**Comment by PhiSpel** [comment]
We still build with an older version, is this intended, @joergbrech ? See #310 , if we can always get the latest version?

https://github.com/joergbrech/Modellbildung-und-Simulation/blob/d3543e9688f0f829daf178322e9c9aa32d3da4c7/requirements.txt#L1

**Comment by PhiSpel** [comment]
In #460, `copy to clipboard` is no longer put into the code box

**Comment by PhiSpel** [comment]
> In #460, `copy to clipboard` is no longer put into the code box

nvm, it still shows up

**Comment by PhiSpel** [comment]
Finally, I don't get the `copy to clipboard` issue any more!

@Florian314, can you just quickly confirm this by opening [https://hbrs-cse.github.io/Modellbildung-und-Simulation/intro.html](https://hbrs-cse.github.io/Modellbildung-und-Simulation/intro.html) and activating **live code** on the top right - does `copy to clipboard` show up in the code box?

**Comment by PhiSpel** [comment]
This issue can be closed as it was solved by updating our jupyter-book version.

As @joergbrech , Chris, and Steve are doing amazing work over at https://github.com/executablebooks/sphinx-thebe/pull/60, I expect we will not need to revert the jupyter-book version. And, anyway, we would not be able to close this issue on the older version.
