### ISSUE TITLE
Discuss usage of jupytext

### ISSUE THREAD

**Issue by joergbrech** [hbrs-cse/Modellbildung-und-Simulation#266]
Since jupyter notebooks are such a nuisance in combination with git, we could discuss wether we want to use something like https://jupytext.readthedocs.io/en/latest/index.html. I haven't checked it out yet, but supposedly its a valid workaround, where we just keep the plain text files in version control and the jupyter notebooks are generated from it somehow. This could be done automatically as part of Continuous Integration.

**Comment by PhiSpel** [comment]
@joergbrech as we will not be doing any large changes anymore, I don't think we need to transfer to jupytext. What do you think?

**Comment by joergbrech** [comment]
I agree, we should not unnecessarily complicated things. IMHO this issue can be closed
