### ISSUE TITLE
Add non-linear approximation exercise

### ISSUE THREAD

**Issue by PhiSpel** [hbrs-cse/Modellbildung-und-Simulation#270]
Curve-fitting, e.g. a*e^(bx)

- hydraulic damper, maybe reference brs motorsport
- only create resulting non-linear system of equations
- For solving the system: https://joergbrech.github.io/Modellbildung-und-Simulation/06_nichtlineare_gleichungen/02_bierschaumzerfall.html

**Comment by PhiSpel** [comment]
@rstrickstrock do you think you will still manage to get on with this, or should we remove your assignment?

**Comment by rstrickstrock** [comment]
I don't know if I will have the time to add an exercise. I would leave the assignment as is, but if anyone else wants to this feel free to take over.

**Comment by PhiSpel** [comment]
merged this issue into #574
