### ISSUE TITLE
Explore color-blind-friendly graphics

### ISSUE THREAD

**Issue by PhiSpel** [hbrs-cse/Modellbildung-und-Simulation#277]
There are attempts such as [colormap](https://de.mathworks.com/matlabcentral/fileexchange/46802-color-blind-friendly-colormap), but how color-blind-friendly are the default Matlab graphics? Do we need to change them?

Can we make some lines wider?

**Comment by LeaKruehler** [comment]
Is there an easy way to to put links or similar in here to collect all the images and graphics that might need changing?

**Comment by PhiSpel** [comment]
e.g. 

https://github.com/joergbrech/Modellbildung-und-Simulation/blob/master/content/00_einleitung/01_motivation/00_motivation.ipynb#26

**Comment by PhiSpel** [comment]
I will check the side using Color Oracle (http://colororacle.org/)
