### ISSUE TITLE
Verwendung dieses Buches | nok Florian

### ISSUE THREAD

**Issue by Florian314** [hbrs-cse/Modellbildung-und-Simulation#313]
-I wasn't able to run the MOxUnit code boxes successfully. With the workaround that is described at the end of the page i still wasn't able to get the result described in the Text below. (neither in Live Code nor in Binder)

-I wasn't able to make MOxUnit work on my Matlab-installation by following the instructions. I tried it on two different Systems. If there is a trick to it this should be added to the instructions.

(Not a problem but annoying: If I activate Live Code and then open "click to hide" every click in the now open Code deletes the line of the code and replace it with "click to hide". (Can only be solved by reloading the Page))

**Comment by PhiSpel** [comment]
> -I wasn't able to run the MOxUnit code boxes successfully. With the workaround that is described at the end of the page i still wasn't able to get the result described in the Text below. (neither in Live Code nor in Binder)
> 
> -I wasn't able to make MOxUnit work on my Matlab-installation by following the instructions. I tried it on two different Systems. If there is a trick to it this should be added to the instructions.

I was able to replicate the error. The file test_fac.m was not found in the current working directory. This may be related to #112 .

`error: Parameter not recognised or file missing: ../test_fac.m`
 
> (Not a problem but annoying: If I activate Live Code and then open "click to hide" every click in the now open Code deletes the line of the code and replace it with "click to hide". (Can only be solved by reloading the Page))

The `click to hide` is actually only overlaying the code. The code below is preserved and executed when clicked. However, we should consider not using the `hide_input` tag and instead a `:class: dropdown` admonition.

**Comment by PhiSpel** [comment]
@Florian314 anything new on this end?

**Comment by Florian314** [comment]
The click to hide Problem is gone. But MoXUnit still doesn't work for me. I tried multiple different things but nothing worked

**Comment by PhiSpel** [comment]
@Florian314 can you approach me to try and fix this together?
