### ISSUE TITLE
Update list_of_all_resources.md

### ISSUE THREAD

**Issue by PhiSpel** [hbrs-cse/Modellbildung-und-Simulation#315]
The [list_of_all_resources.md](https://github.com/joergbrech/Modellbildung-und-Simulation/blob/master/docs/List_of_all_resources.md) may be a bit behind

**Comment by PhiSpel** [comment]
@Florian314 @LeaKruehler can this be done together with #269 ? Or even included?

**Comment by LeaKruehler** [comment]
Thats a good idea! 
I'll include the rescources to the spreadsheet. :)

**Comment by LeaKruehler** [comment]
I guess, this issue can be closed. Its being dealt with in #269 and #212

**Comment by LeaKruehler** [comment]
Oh, my bad! I confused resources with references!

**Comment by PhiSpel** [comment]
This will be dealt with in #158
