### ISSUE TITLE
Page count with JB?

### ISSUE THREAD

**Issue by PhiSpel** [hbrs-cse/Modellbildung-und-Simulation#349]

**Comment by PhiSpel** [comment]
https://jupyterbook.org/en/stable/advanced/html.html#enable-google-analytics should help

**Comment by joergbrech** [comment]
https://analytics.google.com/analytics/web/?pli=1#/report-home/a134708516w194759308p190115755

@team, if you send me your gmail adresses, I can grant you access.

**Comment by PhiSpel** [comment]
According to the response in [](https://stackoverflow.com/questions/50436366/add-view-count-to-webpage-from-google-analytics), we can

1. push the data to a google sheet using a plug-in
2. publish the sheet
3. access the sheet via API

To me, this sounds like a project for future-me (or future-you 😄 )

**Comment by PhiSpel** [comment]
merged this issue into #576
