### ISSUE TITLE
Simplify Bierschaumzerfall

### ISSUE THREAD

**Issue by PhiSpel** [hbrs-cse/Modellbildung-und-Simulation#356]
last exercise may be a bit too much

**Comment by rstrickstrock** [comment]
changed all the issues mentioned.

added the question if exercise 3 should be optional (in the header). Discuss this point and take action based on the decision. Pull/Merge afterwards.

**Comment by PhiSpel** [comment]
https://github.com/hbrs-cse/Modellbildung-und-Simulation/blob/edac183e12a22cd46801c53a8d87e82a906e088c/content/06_nichtlineare_gleichungen/02_bierschaumzerfall.ipynb?short_path=4ebb3b2#L513

This still refers to other exercise numbers

I think we can rename exercise 3 to "Zusatzaufgabe". The headers should also be reconsidered, then: "Optimierungsverfahren" would be part of the "optional" chapter, requiring an admonition.
I suggest splitting the exercise in two, one application-specific introduction and one generalized optimization algorithm.

**Comment by rstrickstrock** [comment]
I changed the numbers the exercise is referring to.
Also changed the title of exercise 3. Kept "Aufgabe 3" but put an "(optional)" behind it, like suggested.
