### ISSUE TITLE
Exercises P3 A1

### ISSUE THREAD

**Issue by rstrickstrock** [hbrs-cse/Modellbildung-und-Simulation#358]
- [x] use "fsolve" instead of "fzero"

- [x] fsolve requires an installed optimization toolbox -> add to one of the first exercises/lectures: when installing matlab check opt toolbox.
-  [x] general formulation; got many questions about how the questions are meant. e.g. in A1 (online book) there are no questions to answer, just code to implement. 
- [x] reference numbers are wrong
- [x] exclude exercise 3 (from the pdf, do not remove in the book)

**Comment by PhiSpel** [comment]
@rstrickstrock @m-r-schenk what's your current progress? Your branch 358-rs/exercise-p3-a1 is not ahead of master

**Comment by rstrickstrock** [comment]
i think this is somehow liked to #356 and when the pull request is done this issue can also be closed?

**Comment by PhiSpel** [comment]
I don't know, but looks like it ;) I'll link the PR to both issues
