### ISSUE TITLE
Syle Guide Text citation

### ISSUE THREAD

**Issue by PhiSpel** [hbrs-cse/Modellbildung-und-Simulation#406]
Aktuell steht da nur

> Die Angabe von Textquellen erfolgt wie????

**Comment by LeaKruehler** [comment]
Ich glaube, das war nur ein Platzhalter, falls wir Textquellen einbinden. Ich glaube, wir haben keine direkten Zitate, oder erinnere ich mich falsch?

**Comment by PhiSpel** [comment]
Ok, ich habe einfach mal geschrieben, dass es nach IEEE erfolgt. Darin sind direkte Zitate genauso wie Literaturangaben (die wir verwenden) definiert.
