### ISSUE TITLE
Stabilität des expliziten versus impliziten Eulerverfahrens | Florian nok

### ISSUE THREAD

**Issue by Florian314** [hbrs-cse/Modellbildung-und-Simulation#418]
- [x] In the chapter Lamda is used as letter for the Lipschitz-Konstante and the constant value in the Prothero-Robinson-Gleichungen. It should be change to prevent misunderstandings for example: The Lipschitz-Konstantecould be change into L instead of Lamda. (L is just an example because it is used by Wikipedia)

- [x] The derivation of y_(k+1)=(y_k+h*λ*g)/(1+h*λ) should be explanied in more detail, because their are to many steps that are skiped between the equation before an this equation. Your average Stundent will probably not understand it.

**Comment by PhiSpel** [comment]
> [ ] In the chapter Lamda is used as letter for the Lipschitz-Konstante and the constant value in the Prothero-Robinson-Gleichungen. It should be change to prevent misunderstandings for example: The Lipschitz-Konstantecould be change into L instead of Lamda. (L is just an example because it is used by Wikipedia)

Good point! L is also used by [Uni Siegen](https://www.math.uni-sb.de/ag/wittstock/lehre/WS00/analysis1/Vorlesung/node48.html)
