### ISSUE TITLE
Rutschendes Masse-Feder-Masse System | nok Florian

### ISSUE THREAD

**Issue by Florian314** [hbrs-cse/Modellbildung-und-Simulation#439]
- "Die Zeit tA durch Analyse einer Schwingungsbewegung allgemein gelöst werden. Danach nutzen Sie den Energieerhaltungssatz." is a task i was not able to do. I am wondering how to bring time into energy conservation. If this task is not solveable we should change it. It it is solveable there is still a word in the sentence missing? I thougt it is "kann" : "Die Zeit tA KANN durch Analyse einer Schwingungsbewegung allgemein gelöst werden."

-  In Task three the form of q for the plotboxes function should be given. I read it from the plotboxes function but in generell this shouldn't be the way ? ( q=[x1; x2; x1_dot; x2_dot] )

**Comment by PhiSpel** [comment]
> * "Die Zeit tA durch Analyse einer Schwingungsbewegung allgemein gelöst werden. Danach nutzen Sie den Energieerhaltungssatz." is a task i was not able to do. I am wondering how to bring time into energy conservation. If this task is not solveable we should change it. It it is solveable there is still a word in the sentence missing? I thougt it is "kann" : "Die Zeit tA KANN durch Analyse einer Schwingungsbewegung allgemein gelöst werden."

I corrected the typo. The solution is not trivial, but the task was given as is in our Physics class. As it is the last of the ODE exercises, I think the difficulty is appropriate.

> * In Task three the form of q for the plotboxes function should be given. I read it from the plotboxes function but in generell this shouldn't be the way ? ( q=[x1; x2; x1_dot; x2_dot] )

As this is the last exercise, I think it it appropriate to use `plotboxes` by scanning through the code. I also swapped the indices to $q=[x1; x1_dot; x2; x2_dot]$ - the different indices should be apparent :)
![untitled](https://user-images.githubusercontent.com/62760840/200343530-dd229a3f-e447-4986-8116-3b38c9b467c4.jpg)

**Comment by Florian314** [comment]
ok, i agree

**Comment by Florian314** [comment]
Different point:
![image](https://user-images.githubusercontent.com/62878881/200539187-fef1062d-0b23-492a-a88a-1f08f6df4b4b.png)

Why is the potential Energie constant and why ist ekin2 never 0 even if the velocity is sometime 0?

**Comment by PhiSpel** [comment]
This is a cumulative plot (I should probably specify this, see #444), so e.g. at $t=0.75 \text{s}$ the $E_\text{pot}$ _and_ $E_\text{kin}_1$ are 0
