### ISSUE TITLE
run circleCI in venv?

### ISSUE THREAD

**Issue by PhiSpel** [hbrs-cse/Modellbildung-und-Simulation#456]
I just noticed the warning under installing requirements:

`WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv`

Maybe we should try to run pip in a venv?

**Comment by joergbrech** [comment]
We could probably also update the docker image we use, currently we are using a legacy docker image running Python 3.6. The latest python release is 3.11. 

https://circleci.com/developer/images/image/cimg/python
