### ISSUE TITLE
Move to ORCA

### ISSUE THREAD

**Issue by PhiSpel** [hbrs-cse/Modellbildung-und-Simulation#467]
- [x] create new tag for zenodo (after #530)
- [x] check affiliations in new zenodo citation
- [x] not possible yet: use latest versions of python and jupyter-notebook
- [x] _no need to_ create mirror, see #437 
- [x] make sure they applied everything correctly

**Comment by joergbrech** [comment]
Currently, the automatic update of my "mirror" fails: https://github.com/joergbrech/Modellbildung-und-Simulation/actions. I am using [aormsby/Fork-Sync-With-Upstream-action](https://github.com/aormsby/Fork-Sync-With-Upstream-action) which merges upstream changes, while I think it would be fine/more stable to just rebase and furce update for our use case. We should check if the action has this option - and if it doesn't see if we can hand-code something that suits our needs.

**Comment by PhiSpel** [comment]
Looks fine now
