### ISSUE TITLE
Approximation von periodischen Signalen | Florian nok 

### ISSUE THREAD

**Issue by Florian314** [hbrs-cse/Modellbildung-und-Simulation#493]
There are not enough Information on DFT. It is nearly impossible for a "normal" Student to just code a DFT without prior Information. 
Of course there are information on the internet but learning such an difficult topic on your one is not realistic. 

By-the-way: I am not a great fan of naming the topic "DFT" and then having the first Task being: Code a DFT

**Comment by PhiSpel** [comment]
Good point! Can you create a new exercise or add slightly smaller steps to this exercise?
