### ISSUE TITLE
Complete thread of LSM 

### ISSUE THREAD

**Issue by PhiSpel** [hbrs-cse/Modellbildung-und-Simulation#495]
The LSM is useful for several problems. Cross-reference this sensibly

**Comment by PhiSpel** [comment]
this is related to #356

**Comment by rstrickstrock** [comment]
Do we still need this?

**Comment by PhiSpel** [comment]
It was your idea :) I think we can move it to `low-priority`

**Comment by rstrickstrock** [comment]
then let's just close it :D

**Comment by PhiSpel** [comment]
I'll add it as a bulltepoint to #157
