### ISSUE TITLE
Durchhang eines flexiblen Kabels dy/dt -> dy/dx

### ISSUE THREAD

**Issue by Florian314** [hbrs-cse/Modellbildung-und-Simulation#500]
I think there is an typing errror: Should be dy/dt -> dy/dx right?

**Comment by Florian314** [comment]
By-the-way: I like that task a lot

**Comment by PhiSpel** [comment]
> I think there is an typing errror: Should be dy/dt -> dy/dx right?

I think so, too.

While you're at it, can you change the second "x=" to just "x"? The mathrm should only be used for units, not for variables.

https://github.com/hbrs-cse/Modellbildung-und-Simulation/blob/f82f71552e70915b136e4d36b877c171e60a8fb3/content/10_bvp/01_durchhang_eines_flexiblen_kabels.ipynb?short_path=1b1eecd#L48
