### ISSUE TITLE
Octave-symbolic not found

### ISSUE THREAD

**Issue by PhiSpel** [hbrs-cse/Modellbildung-und-Simulation#542]
https://github.com/hbrs-cse/Modellbildung-und-Simulation/blob/d883032b6ad7220dbe682a1a0b0e56b4889f6a29/.binder/apt.txt#L2

Lately, binder does not find `octave-symbolic` via apt. @joergbrech, do we even use the symbolic package? If yes, I'll try changing `.binder/apt.txt` to install `symbolic` and hope it works.

**Comment by PhiSpel** [comment]
I checked the apt repos with `apt-cache search`. `octave-symbolic` does not seem to be available anymore, `symbolic` neither. I suggest letting go of the package.

**Comment by joergbrech** [comment]
Ok. I am not sure why it was added in the first place.

**Comment by PhiSpel** [comment]
Does it make sense to also remove `octave-miscellaneous` to prevent future issues?
