### ISSUE TITLE
Auto-update current year in copyright field

### ISSUE THREAD

**Issue by PhiSpel** [hbrs-cse/Modellbildung-und-Simulation#570]

**Comment by PhiSpel** [comment]
@reitd000 this does not seem to work

**Comment by PhiSpel** [comment]
@reitd000 we can, however, keep the copyright to one year, i.e. the alpha release-year. @joergbrech does this make sense?

**Comment by joergbrech** [comment]
To my understanding (which is not much), the year doesn't carry too much meaning. If we want a year in the copyright, it should at least include the first publication date. So I propose to go for the simplest solution. https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated

**Comment by joergbrech** [comment]
If you really want to auto-update, I think the simplest solution would be to script something that edits the yaml before building in CI, e.g. with sed or with python and a suitable yaml lib

**Comment by PhiSpel** [comment]
I agree, we should take the year of first publication, i.e. 2019 (see zenodo). Thank you @joergbrech !
